<script lang="ts" setup></script>

<template>
    <a-layout-content :style="{ margin: '24px 16px 0', overflow: 'initial', overflowX: 'hidden' }">
        <div :style="{ padding: '24px', background: '#fff', textAlign: 'center' }">
            ...
            <br />Really
            <br />...
            <br />...
            <br />...
            <br />long
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />...
            <br />content
        </div>
    </a-layout-content>
</template>